import {actor,failure,operator} from '../../../lib/access';import {database} from '../../../lib/db';
export const dynamic='force-dynamic';
export async function GET(){try{const a=await actor();const db=database();let filter='',params:unknown[]=[];if(a.role==='student'){filter=' AND p.user_id=$1';params=[a.id]}else if(a.role==='college_coordinator'){filter=' AND i.id=$1';params=[a.institution_id]}else if(a.role==='trainer'){filter=' AND EXISTS(SELECT 1 FROM sessions s WHERE s.group_id=g.id AND s.trainer_id=$1)';params=[a.id]}
const students=await db.query('SELECT p.user_id,p.group_id,p.dos_id,u.name,g.name AS group_name,i.name AS institution,i.id AS institution_id FROM student_profiles p JOIN "user" u ON u.id=p.user_id JOIN groups g ON g.id=p.group_id JOIN batches b ON b.id=g.batch_id JOIN institutions i ON i.id=b.institution_id WHERE true'+filter+' ORDER BY u.name',params);
let sf='',sp:unknown[]=[];if(a.role==='student'){sf=' AND s.group_id=(SELECT group_id FROM student_profiles WHERE user_id=$1)';sp=[a.id]}else if(a.role==='trainer'){sf=' AND s.trainer_id=$1';sp=[a.id]}else if(a.role==='college_coordinator'){sf=' AND i.id=$1';sp=[a.institution_id]}
const sessions=await db.query('SELECT s.*,w.title,w.objective,g.name AS group_name,i.name AS institution FROM sessions s JOIN workshops w ON w.id=s.workshop_id JOIN groups g ON g.id=s.group_id JOIN batches b ON b.id=g.batch_id JOIN institutions i ON i.id=b.institution_id WHERE true'+sf+' ORDER BY starts_at DESC',sp);
const cohorts=['organiser','super_admin'].includes(a.role)?(await db.query('SELECT g.id,g.name,b.name AS batch,i.id AS institution_id,i.name AS institution,i.kind,b.capacity,count(p.user_id)::integer AS enrolled FROM groups g JOIN batches b ON b.id=g.batch_id JOIN institutions i ON i.id=b.institution_id LEFT JOIN student_profiles p ON p.group_id=g.id GROUP BY g.id,b.id,i.id ORDER BY i.name,g.name')).rows:[];
const institutions=['organiser','super_admin'].includes(a.role)?(await db.query('SELECT id,name,kind FROM institutions ORDER BY name')).rows:[];
const trainers=['organiser','super_admin'].includes(a.role)?(await db.query(`SELECT u.id,u.name FROM "user" u JOIN role_assignments r ON r.user_id=u.id WHERE r.role='trainer' ORDER BY u.name`)).rows:[];
const emailLogs=['organiser','super_admin'].includes(a.role)?(await db.query(`SELECT id,email,name,role,email_status,created_at FROM invitations ORDER BY created_at DESC LIMIT 30`)).rows:[];
const attendance=a.role==='college_coordinator'?(await db.query(`SELECT at.student_id,at.session_id,at.status,u.name AS student_name,w.title AS session_title,s.starts_at FROM attendance at JOIN "user" u ON u.id=at.student_id JOIN student_profiles p ON p.user_id=at.student_id JOIN groups g ON g.id=p.group_id JOIN batches b ON b.id=g.batch_id JOIN sessions s ON s.id=at.session_id AND s.group_id=g.id JOIN workshops w ON w.id=s.workshop_id WHERE b.institution_id=$1 AND at.status='Absent – Unconfirmed' ORDER BY s.starts_at DESC`,[a.institution_id])).rows:[];
let submissions:unknown[]=[];if(['organiser','super_admin'].includes(a.role))submissions=(await db.query(`SELECT sub.id,sub.type,sub.reference,sub.status,sub.submitted_at,u.name AS student_name,w.title AS session_title FROM submissions sub JOIN "user" u ON u.id=sub.student_id JOIN sessions s ON s.id=sub.session_id JOIN workshops w ON w.id=s.workshop_id WHERE sub.status IN ('Submitted','Submitted Late','Resubmission Requested') ORDER BY sub.submitted_at`)).rows;else if(a.role==='trainer')submissions=(await db.query(`SELECT sub.id,sub.type,sub.reference,sub.status,sub.submitted_at,u.name AS student_name,w.title AS session_title FROM submissions sub JOIN "user" u ON u.id=sub.student_id JOIN sessions s ON s.id=sub.session_id JOIN workshops w ON w.id=s.workshop_id WHERE s.trainer_id=$1 AND sub.status IN ('Submitted','Submitted Late','Resubmission Requested') ORDER BY sub.submitted_at`,[a.id])).rows;
return Response.json({actor:a,students:students.rows,sessions:sessions.rows,cohorts,institutions,trainers,attendance,submissions,emailLogs},{headers:{'Cache-Control':'no-store'}})}catch(e){return failure(e)}}
