'use client';
import {FormEvent,useState} from 'react';
type Cohort={id:string;name:string;batch:string;institution_id:string;institution:string;kind:string;capacity:number;enrolled:number};
export function CohortCard({cohort,canManage,onMessage}:{cohort:Cohort;canManage:boolean;onMessage:(text:string,kind:'success'|'error')=>void}){
 const[open,setOpen]=useState(false);const[editing,setEditing]=useState(false);const[busy,setBusy]=useState(false);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);const response=await fetch('/api/cohorts',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:cohort.id,institution:f.get('institution'),batch:f.get('batch'),group:f.get('group'),capacity:Number(f.get('capacity')),reason:f.get('reason')})});const body=await response.json();if(response.ok){onMessage('Cohort updated.','success');setEditing(false);setTimeout(()=>location.reload(),500)}else onMessage(body.error||'The cohort could not be updated.','error');setBusy(false)}
 async function remove(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!window.confirm('Delete this cohort? This cannot be undone.'))return;setBusy(true);const f=new FormData(e.currentTarget);const response=await fetch('/api/cohorts',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:cohort.id,reason:f.get('reason')})});const body=await response.json();if(response.ok){onMessage('Cohort deleted.','success');setTimeout(()=>location.reload(),500)}else onMessage(body.error||'The cohort could not be deleted.','error');setBusy(false)}
 return <><article className="data-card cohort-card"><p className="eyebrow">{cohort.kind} · {cohort.batch}</p><button className="cohort-link" onClick={()=>setOpen(true)}>{cohort.institution}</button><p>{cohort.name}</p><div className="capacity"><span style={{width:`${Math.min(100,cohort.enrolled/cohort.capacity*100)}%`}}/><div>{cohort.enrolled} of {cohort.capacity} students</div></div></article>{open&&<div className="modal-backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false)}}><section className="modal-panel" role="dialog" aria-modal="true" aria-labelledby={`cohort-${cohort.id}`}><button className="modal-close" onClick={()=>setOpen(false)} aria-label="Close">×</button>{editing?<form onSubmit={save}><p className="eyebrow">EDIT COHORT</p><h3 id={`cohort-${cohort.id}`}>{cohort.institution}</h3><label>Institution<input name="institution" defaultValue={cohort.institution} required/></label><label>Batch<input name="batch" defaultValue={cohort.batch} required/></label><label>Group<input name="group" defaultValue={cohort.name} required/></label><label>Capacity<input name="capacity" type="number" min="1" defaultValue={cohort.capacity} required/></label><label>Reason<textarea name="reason" required/></label><button className="button" disabled={busy}>{busy?'Saving…':'Save changes'} ↗</button></form>:<><p className="eyebrow">{cohort.kind} · BATCH {cohort.batch}</p><h3 id={`cohort-${cohort.id}`}>{cohort.institution}</h3><p>Group {cohort.name} · {cohort.enrolled} of {cohort.capacity} confirmed seats used.</p>{canManage&&<div className="modal-actions"><button className="button" onClick={()=>setEditing(true)}>Edit cohort ↗</button><form onSubmit={remove}><input name="reason" placeholder="Reason for deletion" required/><button className="danger-button" disabled={busy}>{busy?'Deleting…':'Delete cohort'}</button></form></div>}<p className="modal-hint">Use the programme tools to schedule sessions and invite members for this cohort.</p></>}</section></div>}</>;
}
